// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ikzuejidgrgbyokmzttr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlrenVlamlkZ3JnYnlva216dHRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDg5MTUsImV4cCI6MjA2NDI4NDkxNX0.TAtclLORzmfpfiZpIQh8jJfzpU5N72XHOiQBzikRaew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);